deploy:
	@truffle migrate

compile:
	@npm run compile

deploy-test:
	@truffle migrate --network rinkeby

deploy-main:
	@truffle migrate --network main

test:
	@truffle test

.PHONY: test deploy-main deploy-test compile deploy
